#!/bin/bash
set -e

cd poky
. oe-init-build-env
bitbake core-image-minimal
cd ../..

set +e

rm -rf rootfs
mkdir rootfs
pushd rootfs > /dev/null
CPIO="poky/build/tmp/deploy/images/qemux86-64/core-image-minimal-qemux86-64.cpio.gz"
gzip -dc ../$CPIO | cpio --extract --make-directories --format=newc --no-absolute-filenames

# Auto login for SysV
F="./etc/inittab"
sed -i 's/ttyS0::respawn:\/sbin\/getty 115200 ttyS0/ttyS0::respawn:\/sbin\/getty -a root 115200 ttyS0/' $F
sed -i 's/ttyS1::respawn:\/sbin\/getty 115200 ttyS0/ttyS0::respawn:\/sbin\/getty -a root 115200 ttyS1/' $F
sed -i 's/1:12345:respawn:\/sbin\/getty 38400 tty1/1:12345:respawn:\/sbin\/agetty -a root --noclear 38400 tty1/' $F
F="./bin/start_getty"
sed -i 's/    ${setsid:-} ${getty} -L $1 $2 $3/    ${setsid:-} ${getty} -a root -L $1 $2 $3/' $F

# Change root shell to bash
sed ' /^root/ s#/bin/sh#/bin/bash# ' ./etc/passwd > p
mv p ./etc/passwd

# Auto start test on ttyS0 or tty1
#echo 'if [ $(tty) = "/dev/ttyS0" ]; then'	>> ./home/root/.bash_profile
echo 'if [ $(tty) = "/dev/tty1" ]; then'	>> ./home/root/.bash_profile
echo '	if grep inception=kexec_rebooted /proc/cmdline > /dev/null; then'	>> ./home/root/.bash_profile
echo '		/inception/cloud_tmux_restore'				>> ./home/root/.bash_profile
echo '	fi'								>> ./home/root/.bash_profile
echo 'fi'								>> ./home/root/.bash_profile
popd > /dev/null
