#!/bin/bash

P="$( cd "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )"
IN="$P/monitor_pipe.in"

while [ ! -p $IN ]; do
	sleep 0.1
done

echo 'migrate_set_capability x-ignore-shared on' > $IN
echo 'migrate_set_parameter max-bandwidth 0' > $IN
echo 'stop' > $IN
echo 'migrate "exec:cat > '$P'/mnt/soleen/vm_save"' > $IN
echo 'quit' > $IN
