#!/bin/bash

P="$( cd "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )"

cp ~/.bash_profile $P/bash_profile.orig 
cp $P/bash_profile ~/.bash_profile

# If previous session did not finish cleanly
sudo rm $P/monitor_pipe.in $P/monitor_pipe.out
sudo umount $P/mnt
sudo rmdir $P/mnt

cd $P
sudo kexec -l /boot/vmlinuz --initrd=/boot/initrd.img --reuse-cmdline
resize
tmux new -s pasha 'sudo ./qemu_run force' \; split-window -h  'bash'
reset
sudo kexec -e
