#!/bin/bash

P="$( cd "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )"
rm ~/.bash_profile
mv $P/bash_profile.orig ~/.bash_profile
cd $P 
resize
tmux new -s pasha 'sudo ./qemu_run' \; split-window -h  'sudo ./qemu_restore' \; split-window bash
