#!/bin/bash

P="$( cd "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )"
rm ~/.bash_profile
mv $P/bash_profile.orig ~/.bash_profile
cd $P 
tmux new -s pasha './qemu_run' \; split-window -h  './qemu_restore' \; split-window bash
