#!/bin/bash

mkdir -p /inception/mnt
wipefs -fa /dev/pmem0
mkfs.ext4 /dev/pmem0
mount -o dax /dev/pmem0 /inception/mnt
touch /inception/mnt/vm_mem

mount /dev/nvme0n1p3 /mnt
cp /mnt/boot/bzImage /inception/mnt/
umount /mnt

kexec -l /inception/mnt/bzImage --reuse-cmdline --append="inception=tmux_restore"

cd /inception
resize
tmux new -s inception './cloud_vmm_start' \; split-window -h  './cloud_vm_start' \; split-window bash
umount /inception/mnt
kexec -e
