#!/bin/bash

NUM=$1
if [ "$NUM" -gt 0 ]; then
	NUM=$(($NUM - 1))
else
	bash
	exit
fi

tmux split-window -t inception "/inception/cloud_many_restore $NUM"
tmux select-layout  -t inception  tiled
/inception/cloud_vm_restore $NUM
