#!/bin/bash
set -em

for D in $(ls /inception/mnt/); do
	D=$(basename $D)
	if [[ $D = linux* ]] || [[ $D = windows* ]]; then
		/inception/cloud_vm_snapshot $D &
	fi
done
wait
tmux kill-window -t inception
