#!/bin/bash
set -e

VM_TYPE=linux
VM_NUM=0
NCPU=4
MEM_SIZE=4G

while getopts ":c:m:n:w" opt; do
	case ${opt} in
	c )
	NCPU=$OPTARG
	;;
	m )
	MEM_SIZE=$OPTARG
	;;
	n )
	VM_NUM=$OPTARG
	echo VM_NUM $VM_NUM
	;;
	w )
	VM_TYPE=windows
	;;
	\? ) echo "Invalid option: $OPTARG" 1>&2
	exit 1
	;;
	: ) echo "Invalid option: $OPTARG requires an argument" 1>&2
	exit 1
	;;
	esac
done

VM_NAME=${VM_TYPE}${VM_NUM}
PATH_PREFIX=/inception/mnt
VM_PATH=/inception/mnt/$VM_NAME
VM_SOCKET=/tmp/$VM_NAME.socket
MEM_FILE=$VM_PATH/memory

rm -rf $VM_PATH
mkdir $VM_PATH

if [ "$VM_TYPE" = "windows" ]; then
	cp -r $PATH_PREFIX/images/$VM_TYPE/OVMF $VM_PATH/
	cp $PATH_PREFIX/images/$VM_TYPE/windows-server-2019-2.qcow $VM_PATH/
	KERNEL=$VM_PATH/OVMF/OVMF.fd
	DISK="path=$VM_PATH/windows-server-2019-2.qcow"
	EXTRA_CPU=",kvm_hyperv=on,max_phys_bits=39"
else
	KERNEL=$PATH_PREFIX/images/$VM_TYPE/bzImage
	CMDLINE='console=ttyS0 ip=dhcp quiet'
fi

if [ ! -z ${KERNEL+x} ] && [ ! -f $KERNEL ]; then
	echo "Kernel file is missing: $KERNEL" 1>&2
fi

truncate -s $MEM_SIZE $MEM_FILE

/inception/cloud_hv								\
	--api-socket	$VM_SOCKET						\
	--cpus		boot=$NCPU$EXTRA_CPU					\
	--memory	size=0							\
	--kernel	$KERNEL							\
	--memory-zone	size=$MEM_SIZE,file=$MEM_FILE,shared=on,id=pmem0	\
	--serial	tty							\
	--console	off							\
	--net		tap=							\
	${CMDLINE:+'--cmdline' "$CMDLINE"}					\
	${DISK:+'--disk' "$DISK"}

