#!/bin/bash

t1=$(/inception/vtime)
while [ ! -S /tmp/cloud-hypervisor.sock ]; do
	sleep 0.01
done

if nc 2>&1 | grep -q "BusyBox"; then
	CMD="nc local:/tmp/cloud-hypervisor.sock"
else
	CMD="nc -U /tmp/cloud-hypervisor.sock"
fi

#curl -v --unix-socket /tmp/cloud-hypervisor.sock -i \
#     -X PUT 'http://localhost/api/v1/vm.create'  \
#     -H 'Accept: application/json'               \
#     -H 'Content-Type: application/json'         \
#--data-raw '{"cpus":{"boot_vcpus": 4, "max_vcpus": 4},"kernel":{"path":"/inception/mnt/bzImage"},"cmdline":{"args":"console=ttyS0 ip=dhcp quiet"},"rng":{"src":"/dev/urandom"}, "memory":{"file":"/inception/mnt/vm_mem", "size":107374182400}, "console":{"mode":"Off"}, "serial":{"mode":"Tty"}}'

S=''
S+='PUT /api/v1/vm.create HTTP/1.1\r\n'
S+='Accept: application/json\r\n'
S+='Content-Type: application/json\r\n'
S+='Content-Length: 275\r\n\r\n'
S+='{"cpus":{"boot_vcpus": 4, "max_vcpus": 4},"kernel":{"path":"/inception/mnt/bzImage"},"cmdline":{"args":"console=ttyS0 ip=dhcp quiet"},"rng":{"src":"/dev/urandom"}, "memory":{"file":"/inception/mnt/vm_mem", "size":631242752}, "console":{"mode":"Off"}, "serial":{"mode":"Tty"}}'
S+='PUT /api/v1/vm.boot HTTP/1.1\r\n\r\n'
echo -ne "$S" | $CMD


