#!/bin/bash
set -em

VM_NAME=${1}
VM_PATH=/inception/mnt/vms/$VM_NAME
VM_SNAPSHOT=$VM_PATH/snapshot
VM_SOCKET=/tmp/$VM_NAME.socket

if nc 2>&1 | grep -q "BusyBox"; then
	CMD="nc local:$VM_SOCKET"
else
	CMD="nc -NU $VM_SOCKET"
fi

S=''
S+='PUT /api/v1/vm.resume HTTP/1.1\r\n\r\n'

# wait for socket file in backgroud, and send resume command to it as it appears
while [ ! -S $VM_SOCKET ]; do
	sleep 0.01
done && echo -ne "$S" | $CMD 2>&1 > /dev/null &

/inception/cloud_hv								\
	--api-socket $VM_SOCKET							\
	--restore source_url=file://$VM_SNAPSHOT
