#!/bin/bash

cd /inception

wipefs -f -a /dev/pmem0
mkfs.ext4 -F -m 0 -O ^has_journal /dev/pmem0
mount -o dax /dev/pmem0 /inception/mnt

mount /dev/nvme0n1p2 /mnt
cp -r /mnt/soleen/inception/images /inception/mnt/
umount /mnt

# Load next kernel for kexec
kexec -l /inception/mnt/images/linux/bzImage --reuse-cmdline --append="inception=kexec_rebooted"

# Create new detached session
rm -rf /inception/mnt/windows* /inception/mnt/linux*
resize
tmux new -s inception '/inception/cloud_many_create 8'
kexec -e
