#!/bin/bash

while [ ! -S /tmp/cloud-hypervisor.sock ]; do
	sleep 0.01
done

if nc 2>&1 | grep -q "BusyBox"; then
	CMD="nc local:/tmp/cloud-hypervisor.sock"
else
	CMD="nc -U /tmp/cloud-hypervisor.sock"
fi

S=''
S+='PUT /api/v1/vm.pause HTTP/1.1\r\n\r\n'
echo -ne "$S" | $CMD
