#!/bin/bash
set -e

VM_NAME=${1}
VM_SOCKET=/tmp/$VM_NAME.socket
PATH_PREFIX=/inception/mnt
VM_PATH=/inception/mnt/$VM_NAME
VM_SNAPSHOT=$VM_PATH/snapshot
VM_SNAPSHOT_LEN=${#VM_SNAPSHOT}
LEN=$(($VM_SNAPSHOT_LEN + 30))

rm -rf $VM_SNAPSHOT
mkdir $VM_SNAPSHOT

if nc 2>&1 | grep -q "BusyBox"; then
	CMD="nc local:$VM_SOCKET"
else
	CMD="nc -NU $VM_SOCKET"
fi

#while [ ! -S $VM_SOCKET ]; do
#	sleep 0.01
#done
if [ ! -S $VM_SOCKET ]; then
	echo $VM_SOCKET is missing
	exit
fi

S=''
S+='PUT /api/v1/vm.pause HTTP/1.1\r\n\r\n'
S+='PUT /api/v1/vm.snapshot HTTP/1.1\r\n'
S+='Accept: application/json\r\n'
S+='Content-Type: application/json\r\n'
S+='Content-Length: '$LEN'\r\n\r\n'
S+='{"destination_url":"file://'$VM_SNAPSHOT'/"}'
S+='PUT /api/v1/vmm.shutdown HTTP/1.1\r\n\r\n'
echo -ne "$S" | $CMD
