#!/bin/bash

P="$( cd "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )"

mount /dev/nvme1n1p2 /mnt
cp /mnt/boot/bzImage $P/
cp /mnt/boot/sample_vm_bzImage $P/
umount /mnt

kexec -l $P/bzImage --reuse-cmdline --append="pasha=tmux_restore"

# quiet console=ttyS0,115200 memmap=248G!6G,1G!248G pasha=continue pasha=continue
