#!/bin/bash

QPID=$(ps | grep qemu-system | head -n 1 | awk '{print $1}')

/inception/qemu_cmd 'migrate_set_capability x-ignore-shared on'
/inception/qemu_cmd 'migrate_set_parameter max-bandwidth 0'

t1=$(/inception/vtime)
/inception/qemu_cmd 'stop'
t2=$(/inception/vtime)
echo VM STOP TIME $((t2-t1))

t1=$(/inception/vtime)
/inception/qemu_cmd 'migrate "exec:cat > /inception/mnt/vm_save"'
t2=$(/inception/vtime)
echo VM SAVE TIME $((t2-t1))

t1=$(/inception/vtime)
echo "quit" > /inception/monitor_pipe.in
while [ -d /proc/$QPID ]; do
	sleep 0.01
done
t2=$(/inception/vtime)
echo QEMU QUIT TIME $((t2-t1))
