#!/bin/bash

while [ ! -p /inception/monitor_pipe.in ]; do
	sleep 0.01
done

echo "$@" > /inception/monitor_pipe.in

# Wait for previous command to finish by issuing a junk command and
# wait for uknown command to appear
echo -e "garbage_junk\n" > /inception/monitor_pipe.in
grep -qm 1 "unknown command" /inception/monitor_pipe.out
