#!/bin/bash

while [ ! -p /inception/monitor_pipe.in ]; do
	sleep 0.01
done

for ((i = 0; i < 5; i++)); do
	echo 'migrate_set_capability x-ignore-shared on' > /inception/monitor_pipe.in
	echo 'migrate_set_parameter max-bandwidth 0' > /inception/monitor_pipe.in
	echo 'migrate_incoming "exec:cat /inception/mnt/vm_save"' > /inception/monitor_pipe.in
	sleep 0.1	# How do we fix it?
	echo 'cont' > /inception/monitor_pipe.in
	sleep 0.1	# How do we fix it?
	echo 'cont' > /inception/monitor_pipe.in
	sleep 0.1	# How do we fix it?
	echo 'cont' > /inception/monitor_pipe.in
done
