#!/bin/bash

t1=$(/inception/vtime)
while [ ! -p /inception/monitor_pipe.in ]; do
	sleep 0.01
done

/inception/qemu_cmd 'migrate_set_capability x-ignore-shared on'
/inception/qemu_cmd 'migrate_set_parameter max-bandwidth 0'
t2=$(/inception/vtime)
echo QEMU START TIME $((t2-t1))

t1=$(/inception/vtime)
/inception/qemu_cmd 'migrate_incoming "exec:cat /inception/mnt/vm_save"'
t2=$(/inception/vtime)
echo VM RESTORE TIME $((t2-t1))

t1=$(/inception/vtime)
while true ; do
	# Not sure why this is needed ...
	/inception/qemu_cmd 'cont'
	echo 'info status' > /inception/monitor_pipe.in
	L=$(grep -m 1 "VM status" /inception/monitor_pipe.out | awk '{print $3}')
	[[ "running" = $L ]] && break
	
done
t2=$(/inception/vtime)
echo VM RESUME TIME $((t2-t1))
sleep 5
