#!/bin/bash

rm /home/root/.profile

if [ $(tty) = "/dev/ttyS0" ] ; then
	if grep inception=tmux_restore /proc/cmdline > /dev/null; then
		/inception/tmux_restore
	elif grep inception=tmux_create /proc/cmdline > /dev/null; then
		/inception/tmux_create
	fi
fi
