#!/bin/bash

# If previous session did not finish cleanly
rm /inception/monitor_pipe.in /inception/monitor_pipe.out
umount /inception/mnt
rmdir /inception/mnt
cd /inception

# Copy main kernel, and qemu test image
mount /dev/nvme1n1p2 /mnt
cp /mnt/boot/bzImage /inception/
cp /mnt/boot/sample_vm_bzImage /inception/
umount /mnt

# Load next kernel for kexec
kexec -l /inception/bzImage --reuse-cmdline --append="inception=tmux_restore"

resize
tmux new -s inception './qemu_run force' \; split-window -h  'bash'

# Execute next kernel
kexec -e
