#!/bin/bash
set -em

/inception/lin_vm_commands 1
/inception/lin_vm_commands 3
/inception/lin_vm_commands 5
/inception/lin_vm_commands 7
/inception/win_vm_commands 0 &
/inception/win_vm_commands 2 &
/inception/win_vm_commands 4 &
/inception/win_vm_commands 6 &
wait
