#!/bin/bash
N=${1}
P="tmux send-keys -t inception:0.$N "
$P "cmd" Enter
sleep 1
$P "ch -sn Cmd0001" Enter
sleep 0.1
$P "" Enter	# Press Any Key
sleep 0.1
$P "administrator" Enter
sleep 0.1
$P "" Enter	# Domain
sleep 0.1
$P "Admin123" Enter
sleep 0.1
$P "powershell" Enter; $P Enter
sleep 0.1
$P "for (;){Write-Host Windows VM$N' ' -NoNewLine; get-date -format h"
sleep 0.5
$P "h:m"
sleep 0.5
$P "m:s"
sleep 0.5
$P "s; start-sle"
sleep 0.5
$P "ep 1}" Enter; $P Enter
